import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ApolloWrapper from "@/components/AppoloWrapper";
import EmployeeProvider from "./_context/employeeContext";
import { Toaster } from "sonner";
import LeaveRequestProvider from "./_context/leaveRequestContext";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const token =
    typeof window !== "undefined" ? localStorage.getItem("token") || "" : "";
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloWrapper>
          <EmployeeProvider key={token}>
            <LeaveRequestProvider>
              <Toaster />
              {children}
            </LeaveRequestProvider>
          </EmployeeProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
